plugins { id("com.android.application") }

android {
    namespace = "com.research.ambulator"
    compileSdk = 34
    defaultConfig {
        applicationId  = "com.research.ambulator"
        minSdk         = 27
        targetSdk      = 34
        versionCode    = 1
        versionName    = "1.0"
    }
    buildTypes {
        release { isMinifyEnabled = false }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}

dependencies {
    compileOnly("de.robv.android.xposed:api:82")
    implementation("androidx.appcompat:appcompat:1.7.0")
    implementation("com.google.android.material:material:1.12.0")
    implementation("androidx.cardview:cardview:1.0.0")
}
